### ISSUE TITLE
json is not a human editable language for configuration

### ISSUE THREAD

**Issue by eoli3n** [stefanSchinkel/gantt#14]
The purpose of json is to be serializable, to talk from machine to machine.
Human talk to machine with yaml or toml.
Humans are not machines :)

**Comment by stefanSchinkel** [comment]
As much as I enjoy the occasional semantic subtleties, I am not quite sure if the general argument is valid. Human readable (for me at least) refers to: _can edit in vi without any hassle_ (eg. JSON, YAML, CSV...) as opposed to machine readable (elf, mach-o, exe). 

And i kinda assume I am not totally alone in that line of thinking, at least json.org reads: _"JSON (JavaScript Object Notation) is a lightweight data-interchange format. It is **easy for humans to read and write**"_ (emphasis by me). 

I'm also taking the liberty of closing that issue.

**Comment by eoli3n** [comment]
JSON easy to write for a human :laughing: what a joke ! as much as xml yes

**Comment by abubelinha** [comment]
You are free to use other packages to convert from your preferred format to JSON.
