### ISSUE TITLE
Wrongful

### ISSUE THREAD

**Issue by robotkala** [stefanSchinkel/gantt#2]

**Comment by oskarkala** [comment]
My sample.json


{
  "packages": [
    { "label" : "1",
      "start": 1485420985,
      "end": 1485420987,
      "color": "blue",
      "legend": "GA1.2.74.1479217586"
    },
    { "label" : "2",
      "start": 1485420987,
      "end": 1485420988,
      "color": "blue"
    },
    { "label" : "3",
      "start": 1485420988,
      "end": 1485420988,
      "color": "blue"
    },
    { "label" : "4",
      "start": 1485420989,
      "end": 1485420989,
      "color": "blue"
    },
    { "label" : "5",
      "start": 1485420989,
      "end": 1485420994,
      "milestones" : [1485420990],
      "color": "blue"
    },
    { "label" : "6",
      "start": 1485420994,
      "end": 1485420994,
      "color": "blue"
    },
    { "label" : "7",
      "start": 1485420994,
      "end": 1485420995,
      "milestones" : [4,6],
      "color": "blue"
    }
  ],

"title" : "GA1.2.74.1479217586",
"xlabel" : "time (seconds)",
"xticks" : [1485420985,1485420986,1485420987,1485420988,1485420989,1485420990, 1485420991, 1485420992, 1485420993, 1485420994, 1485420995]
}
