### ISSUE TITLE
No LICENSE file

### ISSUE THREAD

**Issue by seanballais** [stefanSchinkel/gantt#4]
What is `gantt` licensed under?

Btw, kudos to you! We're using `gantt` in our [project](https://github.com/seanballais/mlfq-sim), an open source multi-level feedback queue simulator. Thanks for making this project!

**Comment by stefanSchinkel** [comment]
Hi Sean, 

thanks for using gantt and good the see it's working for you. I hadn't thought about a license yet, but I'll license it under MIT. 

Stefan

**Comment by seanballais** [comment]
Thanks for the update!
