### ISSUE TITLE
Label sort is messing with bar colors and legends

### ISSUE THREAD

**Issue by BarbianiM** [stefanSchinkel/gantt#5]
The label sorting in line 108 was preventing me from get the matching colors (label -> bars -> legend).
I just removed the sorting and got good colors on bars and legends.

**Comment by stefanSchinkel** [comment]
yeah, that's true. I wonder why no one ever stumbled across that yet. :thinking:

**Comment by stefanSchinkel** [comment]
Ok. all set. Thanks for spotting the bug.
